const IconDetail = [
    {
        Icon:1,
        IconImg:"https://developer.accuweather.com/sites/default/files/01-s.png",
        day:true,
        night:false,
        text:"Sunny"
    },
    {
        Icon:2,
        IconImg:"https://developer.accuweather.com/sites/default/files/02-s.png",
        day:true,
        night:false,
        text:"Mostly Sunny"
    },
    {
        Icon:3,
        IconImg:"https://developer.accuweather.com/sites/default/files/03-s.png",
        day:true,
        night:false,
        text:"Partly Sunny"
    },
    {
        Icon:4,
        IconImg:"https://developer.accuweather.com/sites/default/files/04-s.png",
        day:true,
        night:false,
        text:"Intermittent Clouds"
    },
    {
        Icon:5,
        IconImg:"https://developer.accuweather.com/sites/default/files/05-s.png",
        day:true,
        night:false,
        text:"Hazy Sunshine"
    },
    {
        Icon:6,
        IconImg:"https://developer.accuweather.com/sites/default/files/06-s.png",
        day:true,
        night:false,
        text:"Mostly Cloudy"
    },
    {
        Icon:7,
        IconImg:"https://developer.accuweather.com/sites/default/files/07-s.png",
        day:true,
        night:true,
        text:"Cloudy"
    },
    {
        Icon:8,
        IconImg:"https://developer.accuweather.com/sites/default/files/08-s.png",
        day:true,
        night:true,
        text:"Dreary (Overcast)"
    },
    {
        Icon:11,
        IconImg:"https://developer.accuweather.com/sites/default/files/11-s.png",
        day:true,
        night:true,
        text:"Fog"
    },
    {
        Icon:12,
        IconImg:"https://developer.accuweather.com/sites/default/files/12-s.png0",
        day:true,
        night:true,
        text:"Showers"
    },
    {
        Icon:13,
        IconImg:"https://developer.accuweather.com/sites/default/files/13-s.png",
        day:true,
        night:false,
        text:"Mostly Cloudy w/ Showers"
    },
    {
        Icon:14,
        IconImg:"https://developer.accuweather.com/sites/default/files/14-s.png",
        day:true,
        night:false,
        text:"Partly Sunny w/ Showers"
    },
    {
        Icon:15,
        IconImg:"https://developer.accuweather.com/sites/default/files/15-s.png",
        day:true,
        night:true,
        text:"T-Storms"
    },
    {
        Icon:16,
        IconImg:"https://developer.accuweather.com/sites/default/files/16-s.png",
        day:true,
        night:false,
        text:"Mostly Cloudy w/ T-Storms"
    },
    {
        Icon:17,
        IconImg:"https://developer.accuweather.com/sites/default/files/17-s.png",
        day:true,
        night:false,
        text:"Partly Sunny w/ T-Storms"
    },
    {
        Icon:18,
        IconImg:"https://developer.accuweather.com/sites/default/files/18-s.png",
        day:true,
        night:false,
        text:"Sunny"
    },
    {
        Icon:19,
        IconImg:"https://developer.accuweather.com/sites/default/files/19-s.png",
        day:true,
        night:false,
        text:"Sunny"
    },
    {
        Icon:20,
        IconImg:"https://developer.accuweather.com/sites/default/files/20-s.png",
        day:true,
        night:false,
        text:"Sunny"
    },
    {
        Icon:21,
        IconImg:"https://developer.accuweather.com/sites/default/files/21-s.png",
        day:true,
        night:false,
        text:"Sunny"
    },
    {
        Icon:22,
        IconImg:"https://developer.accuweather.com/sites/default/files/22-s.png",
        day:true,
        night:false,
        text:"Sunny"
    },
    {
        Icon:23,
        IconImg:"https://developer.accuweather.com/sites/default/files/23-s.png",
        day:true,
        night:false,
        text:"Sunny"
    },
    {
        Icon:24,
        IconImg:"https://developer.accuweather.com/sites/default/files/24-s.png",
        day:true,
        night:false,
        text:"Sunny"
    },
    {
        Icon:25,
        IconImg:"https://developer.accuweather.com/sites/default/files/25-s.png",
        day:true,
        night:false,
        text:"Sunny"
    },
    {
        Icon:26,
        IconImg:"https://developer.accuweather.com/sites/default/files/26-s.png",
        day:true,
        night:false,
        text:"Sunny"
    },
    {
        Icon:27,
        IconImg:"https://developer.accuweather.com/sites/default/files/27-s.png",
        day:true,
        night:false,
        text:"Sunny"
    },
    {
        Icon:28,
        IconImg:"https://developer.accuweather.com/sites/default/files/28-s.png",
        day:true,
        night:false,
        text:"Sunny"
    },
    {
        Icon:29,
        IconImg:"https://developer.accuweather.com/sites/default/files/29-s.png",
        day:true,
        night:false,
        text:"Sunny"
    },
    {
        Icon:30,
        IconImg:"https://developer.accuweather.com/sites/default/files/30-s.png",
        day:true,
        night:false,
        text:"Sunny"
    },
    {
        Icon:31,
        IconImg:"https://developer.accuweather.com/sites/default/files/31-s.png",
        day:true,
        night:false,
        text:"Sunny"
    },
    {
        Icon:32,
        IconImg:"https://developer.accuweather.com/sites/default/files/32-s.png",
        day:true,
        night:false,
        text:"Sunny"
    },
    {
        Icon:33,
        IconImg:"https://developer.accuweather.com/sites/default/files/33-s.png",
        day:true,
        night:false,
        text:"Sunny"
    },
    {
        Icon:35,
        IconImg:"https://developer.accuweather.com/sites/default/files/34-s.png",
        day:true,
        night:false,
        text:"Sunny"
    },
    {
        Icon:34,
        IconImg:"https://developer.accuweather.com/sites/default/files/35-s.png",
        day:true,
        night:false,
        text:"Sunny"
    },
    {
        Icon:36,
        IconImg:"https://developer.accuweather.com/sites/default/files/36-s.png",
        day:true,
        night:false,
        text:"Sunny"
    },
    {
        Icon:37,
        IconImg:"https://developer.accuweather.com/sites/default/files/37-s.png",
        day:true,
        night:false,
        text:"Sunny"
    },
    {
        Icon:38,
        IconImg:"https://developer.accuweather.com/sites/default/files/38-s.png",
        day:true,
        night:false,
        text:"Sunny"
    },
    {
        Icon:39,
        IconImg:"https://developer.accuweather.com/sites/default/files/39-s.png",
        day:true,
        night:false,
        text:"Sunny"
    },
    {
        Icon:40,
        IconImg:"https://developer.accuweather.com/sites/default/files/40-s.png",
        day:true,
        night:false,
        text:"Sunny"
    },
    {
        Icon:41,
        IconImg:"https://developer.accuweather.com/sites/default/files/41-s.png",
        day:true,
        night:false,
        text:"Sunny"
    },
    {
        Icon:42,
        IconImg:"https://developer.accuweather.com/sites/default/files/42-s.png",
        day:true,
        night:false,
        text:"Sunny"
    },
    {
        Icon:43,
        IconImg:"https://developer.accuweather.com/sites/default/files/43-s.png",
        day:true,
        night:false,
        text:"Sunny"
    },
    {
        Icon:44,
        IconImg:"https://developer.accuweather.com/sites/default/files/44-s.png",
        day:true,
        night:false,
        text:"Sunny"
    }
]

export default IconDetail;